quarkus.application.name=spring-jpa-crud
quarkus.http.port=8080

# H2 in-memory database
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:tododb
quarkus.datasource.username=sa
quarkus.datasource.password=

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
