quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.langchain4j.log-requests-curl=true
quarkus.langchain4j.timeout=30

quarkus.langchain4j.vertexai.anthropic.location=europe-west1
quarkus.langchain4j.vertexai.anthropic.project-id=itpc-gcp-cp-pe-eng-claude
quarkus.langchain4j.vertexai.anthropic.model-id=claude-opus-4-6

# The name of the key for the named config is: chat-model but it could whatever name we prefer to set !
quarkus.langchain4j.vertexai.anthropic.chat-model.thinking.include-thoughts=false