name: "CI - JDK 21 Build"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/project.yml'
  pull_request:
    branches: [ main ]


jobs:
  build-jdk21:
    name: "JDK 21 Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 23
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Build
        run: mvn clean install -DskipTests
